#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
PROJECT_DIR="${SCRIPT_DIR}/.."

cd $PROJECT_DIR
. .env

APP_DIR="/apps/minweb"
APP_BIN="./bin/minweb"
APP_NAME="minweb"
PORT="4532"

COMMANDS="""
mkdir -p ${APP_DIR}
cd ${APP_DIR}
. ~/.nvm/nvm.sh
nvm install 18
nvm use 18
npm i -g pnpm@8.12.0
npm i -g pm2@5.3.0
pnpm i
pnpm build
source .env
pm2 stop ${APP_NAME}
PORT=${PORT} pm2 start 'node dist/server' --name=${APP_NAME} --update-env
"""

rsync -aP --exclude=".git" --exclude="node_modules" --exclude=".env" ./ "${DEPLOY_HOST}:${APP_DIR}"

ssh "${DEPLOY_HOST}" "/bin/bash -c '$COMMANDS'"
