#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
PROJECT_DIR="${SCRIPT_DIR}/.."

cd $PROJECT_DIR
. .env

APP_DIR="/apps/minweb"
APP_BIN="./bin/minweb"
APP_NAME="minweb"
PORT="4532"

COMMANDS="""
set -euxo pipefail
mkdir -p ${APP_DIR}
cd ${APP_DIR}
source ~/.nvm/nvm.sh
source .env
make stop
make kill
make start
"""

go mod tidy
make build
env GOOS=linux GOARCH=amd64 go build -o app
rsync -aP --delete ./app ./Makefile "${DEPLOY_HOST}:${APP_DIR}"

ssh $DEPLOY_HOST "/bin/bash -c '$COMMANDS'"